version: '3'
services:
  server:
    build:
      context: '..'
      dockerfile: './docker/Dockerfile'
    entrypoint: './bin/docker_entrypoint'
    working_dir: '/var/www/localhost/htdocs'
    env_file:
      - 'docker-compose.env'
    ports:
      - '3000:3000'
